name: Deployment pipeline
run-name: Deploy ${{ github.ref_name }} to RPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deployment
        run: |
          curl -X POST "${{ secrets.RPI_DEPLOY_URL }}" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.RPI_DEPLOY_TOKEN }}" \
            -d "{\"version\": \"${{ github.ref_name }}\"}"
