name: Release pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.release.outputs.version }}

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          submodules: recursive

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: |
          npm init -y
          npm install --no-save \
            semantic-release \
            @semantic-release/github \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            conventional-changelog-conventionalcommits

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

          # extract latest tag created by semantic-release
          echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
